### ISSUE TITLE
Código de exemplo em dart

### ISSUE THREAD

**Issue by gustavorozolin** [webmaniabr/DFeToken#1]
Gostaria que disponibilizassem um exemplo em Dart, para evitar um request no server (Java). Obrigado.

**Comment by webmaniabr** [comment]
bom dia @gustavorozolin, obrigado pelo feedback. Adicionado a função em Dart: https://github.com/webmaniabr/DFeToken/blob/main/dfeToken.dart.

Abraço
Equipe Webmania®
